core/urls.py
from django.urls import include, path
from core.views import (
    index,
    add_to_cart, 
    cart_view, 
    update_cart,
    delete_item_from_cart,
    filter_product, 
    product_list_view, 
    product_detail_view, 
    category_list_view, 
    category_product_list__view, 
    tag_list, 
    search_view,
    ajax_add_review,
    checkout_view,
    payment_completed_view,
    payment_failed_view,
    razorpay_payment_success_view,
    customer_dashboard,
    order_details,
    make_address_default,
    wishlist_view,
    add_to_wishlist,
    remove_wishlist,
    contact,
    ajax_contact_form
)

app_name = "core"

urlpatterns = [
    path("",index,name="index"),
    path("category/",category_list_view, name="category-list"),
    path("category/<cid>/",category_product_list__view, name="category-product-list"),
    path("products/",product_list_view, name="product-list"),
    path("products/tag/<slug:tag_slug>/",tag_list, name="tags"),
    path("product/<pid>/",product_detail_view, name="product-detail"),
    path("ajax-add-review/<int:pid>/",ajax_add_review, name="ajax-add-review"),
    path("search/",search_view,name="search"),
    path("filter-products/",filter_product,name="filter-products"),
    path("add-to-cart/",add_to_cart,name="add-to-cart"),
    path("update-cart/",update_cart,name="update-cart"),
    path("delete-from-cart/",delete_item_from_cart,name="delete-from-cart"),
    path("cart/",cart_view,name="cart"),
    path("checkout/",checkout_view,name="checkout"),
    path("paypal/",include("paypal.standard.ipn.urls")),
    path("payment-completed/",payment_completed_view, name="payment-completed"),
    path("payment-failed/",payment_failed_view, name="payment-failed"),
    path("razorpay-payment-success/",razorpay_payment_success_view, name="razorpay-payment-success"),
    path("dashboard/",customer_dashboard, name="dashboard"),
    path("dashboard/order/<int:id>",order_details, name="order-detail"),
    path("make-default-address/",make_address_default, name="make-default-address"),
    path("wishlist/",wishlist_view, name="wishlist"),
    path("add-to-wishlist/",add_to_wishlist, name="add-to-wishlist"),
    path("remove-from-wishlist/",remove_wishlist, name="remove-from-wishlist"),
    path("contact/",contact, name="contact"),
    path("ajax-contact-form/",ajax_contact_form, name="ajax-contact-form"),
]

evergreen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('user/',include('userauth.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

evershine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('user/',include('userauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userauth/urls.py
from django.urls import path
from userauth import views

app_name = "userauth"

urlpatterns = [
    path('sign-up/',views.register_view, name='sign-up'),
    path('sign-in/',views.login_view, name='sign-in'),
    path('sign-out/',views.logout_view, name='sign-out'),
]

core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Write a review'}))

    class Meta:
        model = ProductReview
        fields = ['review','rating']

core/views.py
import calendar
import razorpay
from core.forms import ProductReviewForm
from core.models import Category,Products,ProductReview,CartOrder,CartOrderItems,Address,Wishlist
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.db.models import Avg, Count
from django.db.models.functions import ExtractMonth
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from taggit.models import Tag
from userauth.models import ContactUs, Profile

def index(request):
    products= Products.objects.filter(product_status="published",featured=True)
    context = {"products":products}
    return render(request,'core/index.html',context)

def product_list_view(request):
    products= Products.objects.filter(product_status="published")
    context = {"products":products}
    return render(request,'core/product-list.html',context)

def category_list_view(request):
    categories= Category.objects.all()
    context = {"categories":categories}
    return render(request,'core/category-list.html',context)

def category_product_list__view(request,cid):
    category = Category.objects.get(cid=cid)
    products = Products.objects.filter(product_status="published",category=category)
    context = {"category":category,"products":products}
    return render(request,'core/category-product-list.html',context)

def product_detail_view(request,pid):
    product = Products.objects.get(pid=pid)
    related_products = Products.objects.filter(category=product.category).exclude(pid=pid)
    reviews = ProductReview.objects.filter(product=product).order_by("-date")
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    review_form = ProductReviewForm()
    make_review = True
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user,product=product).count()
        if user_review_count > 0:
            make_review = False
    p_image = product.p_images.all()
    context = {"p":product,"review_form":review_form,"make_review":make_review,"p_image":p_image,"products":related_products,"reviews":reviews,"average_rating":average_rating}
    return render(request,'core/product-detail.html',context)

def tag_list(request,tag_slug=None):
    products = Products.objects.filter(product_status="published")
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug)
        products = products.filter(tags__in=[tag])
    context = {"products":products,"tag":tag}
    return render(request,'core/tag.html',context)

def ajax_add_review(request,pid):
    product = Products.objects.get(pk=pid)
    user = request.user
    review = ProductReview.objects.create(user=user,product=product,review=request.POST['review'],rating=request.POST['rating'])
    context = {"user":user.username,"review":request.POST['review'],"rating":request.POST['rating']}
    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    return JsonResponse({'bool':True,'context':context,'average_reviews':average_reviews})

def search_view(request):
    query = request.GET.get("q")
    products = Products.objects.filter(title__icontains=query).order_by("-added_date")
    context={"products":products,"query":query}
    return render(request,'core/search.html',context)

def filter_product(request):
    categories = request.GET.getlist("category[]")
    min_price = request.GET['min_price']
    max_price = request.GET['max_price']
    products = Products.objects.filter(product_status="published").order_by("-id").distinct()
    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)
    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()
    data = render_to_string("core/async/product-list.html",{"products":products})
    return JsonResponse({"data":data})

def add_to_cart(request):
    cart_product = {}
    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
        'image': request.GET['image'],
        'pid': request.GET['pid']
    }
    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product
    return JsonResponse({"data":request.session['cart_data_obj'], "totalcartitems": len(request.session['cart_data_obj'])})

def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for pid, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
        return render(request,'core/cart.html',{"cart_data":request.session['cart_data_obj'], "totalcartitems": len(request.session['cart_data_obj']),"cart_total_amount":cart_total_amount})
    else:
        messages.warning(request,"Your Cart is empty")
        return redirect("core:index")

def delete_item_from_cart(request):
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for pid, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
    context = render_to_string("core/async/cart-list.html",{"cart_data":request.session['cart_data_obj'], "totalcartitems": len(request.session['cart_data_obj']),"cart_total_amount":cart_total_amount})
    return JsonResponse({"data":context, "totalcartitems": len(request.session['cart_data_obj'])})   

def update_cart(request):
    product_id = str(request.GET['id'])
    product_qty = request.GET['qty']
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[product_id]['qty'] = product_qty
            request.session['cart_data_obj'] = cart_data
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for pid, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
    context = render_to_string("core/async/cart-list.html",{"cart_data":request.session['cart_data_obj'], "totalcartitems": len(request.session['cart_data_obj']),"cart_total_amount":cart_total_amount})
    return JsonResponse({"data":context, "totalcartitems": len(request.session['cart_data_obj'])})          

@login_required
def checkout_view(request):
    cart_total_amount = 0
    total_amount = 0
    if 'cart_data_obj' in request.session:
        for pid, item in request.session['cart_data_obj'].items():
            total_amount += int(item['qty']) * float(item['price'])
        order = CartOrder.objects.create(user=request.user,price=total_amount)
        for pid, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
            CartOrderItems.objects.create(
                order=order,
                invoice_no="INVOICE_NO_"+str(order.id),
                item=item['title'],
                image=item['image'],
                qty=item['qty'],
                price=item['price'],
                total=float(item['qty'])*float(item['price'])
            )
    razorpay_client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))
    razorpay_order = razorpay_client.order.create({
        "amount": cart_total_amount*100,
        "currency": "INR",
        "payment_capture": "1",
    })
    try:
        active_address = Address.objects.get(user=request.user, status=True)
    except:
        messages.warning(request,"There are multiple addresses, only one should be activated.")
        active_address = None
    return render(request, 'core/checkout.html', {"cart_data": request.session['cart_data_obj'], "totalcartitems": len(request.session['cart_data_obj']), "cart_total_amount": cart_total_amount,"razorpay_order_id": razorpay_order['id'],"razorpay_key": settings.RAZORPAY_KEY_ID,"currency": "INR","active_address":active_address})

@csrf_exempt
@login_required
def payment_completed_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for pid, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
    return render(request, 'core/payment-completed.html', {"cart_data": request.session['cart_data_obj'], "totalcartitems": len(request.session['cart_data_obj']), "cart_total_amount": cart_total_amount})

def payment_failed_view(request):
    return render(request,"core/payment-failed.html")

@csrf_exempt
def razorpay_payment_success_view(request):
    return render(request, 'core/razorpay-payment-success.html')

@login_required
@csrf_exempt
def customer_dashboard(request):
    order_list = CartOrder.objects.filter(user=request.user).order_by("-id")

templates/core/checkout.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Shop
                <span></span> Checkout
            </div>
        </div>
    </div>
    <div class="container mb-80 mt-50">
        <div class="row">
            <div class="col-lg-8 mb-40">
                <h1 class="heading-2 mb-10">Checkout</h1>
                <div class="d-flex justify-content-between">
                    <h6 class="text-body">There are <span class="text-brand">{{ totalcartitems }}</span> product{{ totalcartitems | pluralize }} in your cart</h6>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-7">
                <div class="row mb-50">
                    <div class="col-lg-6">
                        <form method="post" class="apply-coupon">
                            <input type="text" placeholder="Enter Coupon Code...">
                            <button class="btn  btn-md" name="login">Apply Coupon</button>
                        </form>
                    </div>
                </div>
                <div class="row">
                    <h4 class="mb-30">Billing Details</h4>
                    <form method="post">
                        <div class="row">
                            <div class="form-group col-lg-6">
                                <input type="text" required="" name="fname" value="{{ request.user.username | title }}" placeholder="First name *">
                            </div>
                            <div class="form-group col-lg-6">
                                <input type="text" required="" name="lname" placeholder="Mobile *" value="{{ active_address.mobile }}">
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-lg-12">
                                <input type="text" name="billing_address" required="" placeholder="Address *" value="{{ active_address.address }}">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="border p-40 cart-totals ml-30 mb-50">
                    <div class="d-flex align-items-end justify-content-between mb-30">
                        <h4>Your Order</h4>
                        <h6 class="text-muted">Subtotal: <span class="text-brand">₹{{ cart_total_amount | floatformat:2 }}</span></h6>
                    </div>
                    <div class="divider-2 mb-10"></div>
                    <a href="{% url 'core:cart' %}" class="btn btn-fill-out btn-block mt-20 mb-20">Go back to cart</a>
                    <div class="table-responsive order_table checkout">
                        <table class="table no-border">
                            <tbody>
                                {% for product_id, item in cart_data.items %}
                                <tr>
                                    <td class="image product-thumbnail"><img src="{{ item.image }}" alt="#"></td>
                                    <td>
                                        <h6 class="w-160 mb-5"><a href="{% url 'core:product-detail' item.pid %}" class="text-heading">{{ item.title }}</a></h6></span>
                                    </td>
                                    <td>
                                        <h6 class="text-muted pl-20 pr-20">x {{ item.qty }}</h6>
                                    </td>
                                    <td>
                                        <h5 class="text-muted">₹{{ item.price }}</h5>
                                    </td>
                                    <td>
                                        <h5 class="text-brand">₹{% widthratio item.price 1 item.qty %}</h5>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="payment ml-30">
                    <h4 class="mb-30">Payment</h4>
                    <div class="payment_option">
                        <div class="custome-radio">
                            <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios3" checked="">
                            <label class="form-check-label" for="exampleRadios3" data-bs-toggle="collapse" data-target="#bankTranfer" aria-controls="bankTranfer">Direct Bank Transfer</label>
                        </div>
                        <div class="custome-radio">
                            <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios4" checked="">
                            <label class="form-check-label" for="exampleRadios4" data-bs-toggle="collapse" data-target="#checkPayment" aria-controls="checkPayment">Cash on delivery</label>
                        </div>
                        <div class="custome-radio">
                            <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios5" checked="">
                            <label class="form-check-label" for="exampleRadios5" data-bs-toggle="collapse" data-target="#paypal" aria-controls="paypal">Online Getway</label>
                        </div>
                    </div>
                    <div class="payment-logo d-flex">
                        <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-paypal.svg' %}" alt="">
                        <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-visa.svg' %}" alt="">
                        <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-master.svg' %}" alt="">
                        <img src="{% static 'assets/imgs/theme/icons/payment-zapper.svg' %}" alt="">
                    </div>
                    <div class="mt-3">
                        <form action="{% url 'core:razorpay-payment-success' %}" method="POST" class="mt-3">
                            {% csrf_token %}
                            <script 
                                src="https://checkout.razorpay.com/v1/checkout.js"
                                data-key="{{ razorpay_key }}" 
                                data-amount="{{ cart_total_amount|floatformat:2|add:0 }}" 
                                data-currency="{{ currency }}"
                                data-order_id="{{ razorpay_order_id }}"
                                data-buttontext="Pay with Razorpay"
                                data-name="Your Store Name"
                                data-description="Secure Payment with Razorpay"
                                data-theme.color="#3399cc">
                            </script>
                        </form>
                    </div>                    
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

templates/core/wishlist.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Shop <span></span> Fillter
            </div>
        </div>
    </div>
    <div class="container mb-30 mt-50">
        <div class="row">
            <div class="col-xl-10 col-lg-12 m-auto">
                <div class="mb-50">
                    <h1 class="heading-2 mb-10">Your Wishlist</h1>
                    <h6 class="text-body">There are <span class="text-brand">5</span> products in this list</h6>
                </div>
                <div class="table-responsive shopping-summery">
                    <table class="table table-wishlist">
                        <thead>
                            <tr class="main-heading">
                                <th class="custome-checkbox start pl-30">
                                    <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="" />
                                    <label class="form-check-label" for="exampleCheckbox11"></label>
                                </th>
                                <th scope="col" colspan="2">Product</th>
                                <th scope="col">Price</th>
                                <th scope="col">Stock Status</th>
                                <th scope="col">Action</th>
                                <th scope="col" class="end">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for w in wishlist %}
                            <tr class="pt-30">
                                <td class="custome-checkbox pl-30">
                                    <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                    <label class="form-check-label" for="exampleCheckbox1"></label>
                                </td>
                                <td class="image product-thumbnail pt-40"><img src="{{ w.product.image.url }}" alt="#" /></td>
                                <td class="product-des product-name">
                                    <h6><a class="product-name mb-10" href="{% url 'core:product-detail' w.product.pid %}">{{ w.product.title | truncatechars:30 }}</a></h6>
                                </td>
                                <td class="price" data-title="Price" style="font-size: 22px;">
                                    <span class="text-brand">₹<span class="text-brand current-product-price-{{ w.product.id }}"><b>{{ w.product.price }}</b></span></span>
                                </td>
                                <td class="text-center detail-info" data-title="Stock">
                                    <span class="stock-status in-stock mb-0"> {% if w.product.in_stock %} In Stock {% else %} Out of Stock {% endif %}</span>
                                </td>
                                <td class="text-right" data-title="Cart">
                                    <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{ w.product.id }}">
                                    <input type="hidden" class="product-pid-{{ w.product.id }}" value="{{ w.product.pid }}" >
                                    <input type="hidden" class="product-image-{{ w.product.id }}" value="{{ w.product.image.url }}">
                                    <input type="hidden" class="product-id-{{ w.product.id }}" value="{{ w.product.id }}">
                                    <input type="hidden" class="product-title-{{ w.product.id }}" value="{{ w.product.title }}">
                                    <button class="btn btn-sm add-to-cart-btn" data-index="{{ w.product.id }}">Add to cart</button>
                                </td>
                                <td class="action text-center" data-title="Remove">
                                    <a href="#" class="text-body"><i class="fi-rs-trash"></i></a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td><p>Nothing in Wishlist yet....</p></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}